docs:
  input: raw_docs
  op: docs

pdoc:
  project: tc
  op: docs

md_vars:
  global:
    project_name: tc
    repo_name: tournament-cutter
    formal_name: Tournament Cutter
    site: tc.comms.whinyaan.xyz
    scripts_url: tc.comms.whinyaan.xyz/scripts
    organization: whinee
    user: whinee
    codacy_id: 71ddc7b8f67c4a589357b6de243e682c
    dc_acc: whi_ne | whinyaan.xyz#5135
    dc_link: https://discord.com/users/867696753434951732
    dc_inv: JbAtUxGcJZ
    mail_acc: whinyaan@pm.me
    mail_link: mailto:whinyaan@pm.me
    desc: |-
      Process tetris tournament videos
    long_desc: |-
      Process tetris tournament videos and cut them appropriately using FFmpeg.

  local:
    README:
      title: Tournament Cutter

rules:
  del:
  repl:
    'src="https://${site}/assets':
      - 'src="./assets'
    "src='https://${site}/assets":
      - "src='./assets"
    "](https://${site}/assets":
      - "](./assets"

requirements:
  dev: dev_req.txt
  prod: requirements.txt

env:
  dev:
    req:
      - prod
      - dev

license:
  year: 2022
  type: MIT
  cholder:
    whi_ne:
      user: whinee
      projects:
        hyaku-dl:
          hyaku:
            year: 2022
            platform: Github
        MangDL:
          MangDL:
            year: 2021-2022
            platform: Github
        Pirate-Kings:
          YAMHL:
            year: 2022
            platform: Github