site_name: Tournament cutter
site_url: https://tc.comms.whinyaan.xyz
repo_url: https://github.com/whinee/tournament-cutter
site_description: |-
  Process tetris tournament videos
site_author: whi~nyaan!
copyright: Copyright &copy; 2022 whitespace_negative

theme:
  name: material
  locale: en
  include_search_page: false
  search_index_only: true
  language: en
  favicon: assets/favicon.png
  logo: images/icons/logo.svg

  font:
    text: Roboto
    code: Roboto Mono

  static_templates:
    - 404.html

  features:
    - navigation.instant
    - navigation.tracking
    - navigation.tabs
    - navigation.sections
    - navigation.indexes

  palette:
    -
      scheme: slate
      primary: deep purple
      accent: deep purple
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
    -
      scheme: default
      primary: deep purple
      accent: deep purple
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode

markdown_extensions:
  -
    pymdownx.superfences:
      custom_fences:
        -
          name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format

extra:
  social:
    -
      icon: fontawesome/brands/github
      link: https://github.com/hyaku-dl/urasunday
    -
      icon: fontawesome/brands/python
      link: https://pypi.org/project/ura/
    -
      icon: fontawesome/brands/twitter
      link: https://twitter.com/whi_nyaan

plugins:
  - search
  - minify:
      minify_html: true
      minify_css: true
      minify_js: true

nav:
  - Home: /

  # Do Not Modify!
  - Installation:
  # nav inst start
    - Index: docs/0/0/installation/
    - Installable:
      - Index: docs/0/0/installation/installable
      - Windows 7 and up: docs/0/0/installation/installable/windows
      - Linux:
        - Index: docs/0/0/installation/installable/linux/
        - Arch: docs/0/0/installation/portable/linux/arch/
        - Debian: docs/0/0/installation/portable/linux/debian/
    - Portable:
      - Index: docs/0/0/installation/portable
      - Windows 7 and up: docs/0/0/installation/portable/windows
      - Linux:
        - Index: docs/0/0/installation/portable/linux/
        - Arch: docs/0/0/installation/portable/linux/arch/
        - Debian: docs/0/0/installation/portable/linux/debian/
    - Programmatic:
      - Index: docs/0/0/installation/programmatic
      - Windows 7 and up: docs/0/0/installation/programmatic/windows
      - MacOS: docs/0/0/installation/programmatic/macos
      - Linux:
        - Index: docs/0/0/installation/programmatic/linux/
        - Arch: docs/0/0/installation/programmatic/linux/arch/
        - Debian: docs/0/0/installation/programmatic/linux/debian/
  # nav inst end

  - License agreement: /license
  - Changelog: /changelog
  - Notes:
    - Notes: /notes
    - Notes to self: /notes to self

  # Do Not Modify!
  - Documentation:
  # nav docs start
    - 0.0 (Current): docs/0/0/
  # nav docs end