<!-- markdownlint-disable MD024 MD025 -->

# 0 0 0 0 0 1

## Changed

- Windows' CFLOP[0] from `.\ura.yml` to `.\tc.yml`

## Removed

- Thumbnail template

# 0 0 0 0 0 0

Initial release of the application
